# Generated by Django 3.0.7 on 2020-07-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='commment',
            new_name='comment',
        ),
    ]
